# Generated by Django 4.2.23 on 2025-10-04 17:37

import authentication_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_make_public_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=authentication_app.models.User._gen_public_id, editable=False, max_length=12, unique=True),
        ),
    ]
