# Generated by Django 4.2.23 on 2025-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reservationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('transferred', 'Transferred')], default='pending', max_length=20),
        ),
    ]
